name = "hive"
version = "1.0.0"
target = "erlang"

description = "A compiler for the Hive language — a memory-managed, table-based language that compiles to Go."

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
simplifile = ">= 2.5.0 and < 3.0.0"
argv = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
